app/v1/users/models.py
from datetime import datetime
import uuid

USERS = []
class User(object):
    '''this class defines the manipulations of a user '''
    def __init__(self, *args, **kwargs):
        self.users = USERS
    def get_user(self):
        pass
    def create_user(self,user_id):
        pass
    def exists(self,user_id):
        pass

app/v1/users/__init__.py
from flask import Blueprint

simple_page = Blueprint('simple_page',__name__,url_prefix='/api/v1/')
home_blueprint = Blueprint('home',__name__,url_prefix='/api/v1/')
login_blueprint = Blueprint('login',__name__,url_prefix='/api/v1/')
signup_blueprint = Blueprint('signup',__name__,url_prefix='/api/v1/')

app/v1/users/views.py
from flask import Blueprint, render_template, abort, request, make_response, jsonify
from jinja2 import TemplateNotFound
from flask.views import MethodView
from . import *

#creating blueprints here 

# simple_page = Blueprint('simple_page',__name__,url_prefix='/api/v1/')
# home_blueprint = Blueprint('home',__name__,url_prefix='/api/v1/')
# login_blueprint = Blueprint('login',__name__,url_prefix='/api/v1/')
# signup_blueprint = Blueprint('signup',__name__,url_prefix='/api/v1/')

# class HomeView(MethodView):
#     '''this is the index page view'''
#     template_name = '/user/index.html'
#     methods=['GET','POST']
#     def dispatch_request(self, *args, **kwargs):
#         if request.method == 'GET':
#             return render_template(self.template_name)
#     # def get(self):
#     #     return render_template(self.template_name)
# @home_blueprint.route('',methods=['GET'])
# def home_view():
#     template_name = '/user/index.html'
#     return render_template(template_name)




# class UserLoginView(MethodView):
#     '''this class allows a user to log into the platform'''
#     template_name = '/auth/login.html'
#     methods=['POST']
#     def dispatch_request(self, *args, **kwargs):
#         if request.method == 'POST':
#             return render_template(self.template_name)
#     # def post(self):
#     #     return render_template(self.template_name)

# @login_blueprint.route('/auth/login',methods=['POST'])
# def login_view():
#     template_name = '/auth/login.html'
#     if request.method == 'POST':
#         return render_template(template_name)
#     else:
#         return {"message":'method not allowed',"status_code":404}

# class UserSignUpView(MethodView):
#     '''this class allows user to create an account'''
#     template_name = '/auth/signup.html'
#     methods=['POST']
#     def dispatch_request(self, *args, **kwargs):
#         if request.method == 'POST':
#             return render_template(self.template_name)
#     # def post(self):
#     #     return render_template(self.template_name)
# @signup_blueprint.route('/auth/register',methods=['POST'])
# def signup_view():
#     template_name = '/auth/signup.html'
#     if request.method == 'POST':
#         return render_template(template_name)
#     else:
#         return {"message":'method not allowed',"status_code":404}

@simple_page.route('/', defaults={'page': 'index'},methods=['GET'])
@simple_page.route('/<page>',methods=['GET','POST'])
def show(page):
    try:
        return render_template('/user/index.html')
    except TemplateNotFound:
        abort(404)

@signup_blueprint.route('/auth/register',methods=['POST'])
def signup_view():
    template_name = '/auth/signup.html'
    if request.method == 'POST':
        return render_template(template_name)
    else:
        return {"message":'method not allowed',"status_code":404}

@login_blueprint.route('/auth/login',methods=['POST'])
def login_view():
    template_name = '/auth/login.html'
    if request.method == 'POST':
        return render_template(template_name)
    else:
        return {"message":'method not allowed',"status_code":404}

@home_blueprint.route('/home',methods=['GET'])
def home_view():
    template_name = '/user/index.html'
    return render_template(template_name)


# class TestMe(MethodView):
#     template_name = '/user/index.html'
#     methods=['GET']
#     def dispatch_request(self, *args, **kwargs):
#         if request.method == 'GET':
#             return render_template(self.template_name)
#         # return super().dispatch_request(*args, **kwargs)


# test_view = TestMe.as_view('testing')
# home_view = HomeView.as_view('home')
# login_view = UserLoginView.as_view('login')
# signup_view = UserSignUpView.as_view('signup')

# home_blueprint.add_url_rule('/home',view_func=home_view)
# login_blueprint.add_url_rule('/auth/login',view_func=login_view)
# signup_blueprint.add_url_rule('/auth/register/',view_func=signup_view)


# simple_page.add_url_rule('',view_func=test_view)

templates/user/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Home</title>
	<link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static',filename='img/quest22.png')}}">
	<link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/questioner.css') }}">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Open+Sans">
</head>
<body>

<div class="header" id="header">
			<a href="{{ url_for('home.home_view')}}" class="logo" style="padding:0%;">
				<span>
					<img src="{{ url_for('static', filename='img/quest22.png')}}" alt="Home">
				</span>
				
			</a>
			<span>
				<input type="search" name="search" class="search" placeholder="search questioner ...">
			</span>
			<span class="user_status" id="user_status">
				<a class="login_button" id="login_button" href="{{ url_for('signup.signup_view')}}">
					<span><i class="fas fa-user-plus" style="padding-right:5px;display: inline-block;"></i></span>
					Sign up
				</a>
				<a class="signup_button" id="signup_button" href="{{ url_for('login.login_view')}}">
					<span><i class="fas fa-sign-in-alt" style="padding-right:5px;display: inline-block;"></i></span>
					Login
				</a>
				<a class="signup_button" id="signup_button" href="#" style="padding: 5px 10px 5px 0px;">
					<span><i class="fas fa-user-circle" style="padding-right:5px;display: inline-block;"></i></span><br>
					<span style="font-size: 13px;color:#ff4949;">logged in as</span>
				</a>
			</span>
		</div>
		<!-- <div id="sidebar-left">Left</div> -->
		<!-- <div class="top_content" id="top_content" style="color: inherit;">
				<h2>Welcome to Questioner. Ready to engage in some mind blowin discussions ? ... checkout latest meetups here</h2>
			</div> -->
			<div class="main" id="main">
					<div class="top_content" id="top_content" style="color: #ff4646;padding-top: 20px;">
						<p>-- Welcome to Questioner. Ready to engage in some mind blowin discussions ? ... checkout latest meetups here --</p>
					</div>
					<div class="meetups">
						<div class="meetup">
						<h3>Ruby / Python </h3>
						<span>
							<img src="{{ url_for('static',filename='img/beef.jpg') }}" style="width: 100%;height: 70%;">
							<button class="rsvp_button" id="rsvp_button"><a href="#" style="text-decoration:none;color:inherit;">RSVP Here</a></button>
						</span>
						<span>
							<p>these are details of meetup one</p>
						</span>
					</div>
					<div class="meetup">
						<h3>Mpesa APIs</h3>
						<span>
							<img src="{{ url_for('static',filename='img/chips.jpg') }}" style="width: 100%;height: 70%;">
							<button class="rsvp_button" id="rsvp_button"><a href="#" style="text-decoration:none;color:inherit;">RSVP Here</a></button>
							<p>these are details of meetup two</p>
						</span>
						<span>
							
						</span>
					</div>
					<div class="meetup">
						<h3>Google APIs</h3>
						<span>
							<img src="{{ url_for('static',filename='img/chicken.jpeg') }}" style="width: 100%;height: 70%;">
							<button class="rsvp_button" id="rsvp_button"><a href="#" style="text-decoration:none;color:inherit;">RSVP Here</a></button>
							<p>these are details of meetup three sssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss
							</p>
						</span>
						<span>
							
						</span>
					</div>
					</div>
			</div>
		
		<div class="footer" id="footer">
			<ul style="margin: 5px;">
			<a href="https://facebook.com">Facebook </a>|
			<a href="https://twitter.com">Twitter </a>|
			<a href="https://instagram.com">Instagram </a>|
			<a href="https://plus.google.com/discover">Google +</a><br>
			<p>Copyright <span>&copy;</span> 2019 Questioner. All Rights Reserved</p>
			</ul>
		</div>
</body>
</html>